# Generated by Django 4.2.8 on 2024-05-17 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='user',
            name='deposit_products',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saving_products',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('current_balance', models.IntegerField(blank=True, null=True)),
                ('annual_salary', models.IntegerField(blank=True, null=True)),
                ('deposit_products', models.ManyToManyField(blank=True, related_name='users', to='products.depositproducts')),
                ('saving_products', models.ManyToManyField(blank=True, related_name='users', to='products.savingproducts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
